import { chromium, expect } from '@playwright/test';
const root = process.env.TEST_BASE_URL || 'http://localhost:3000';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
try {
 const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
 const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
 await page.goto(root); await page.getByText('Good morning, Alex').waitFor();
 const initial = await (await context.request.get(root + '/api/workspace')).json();
 const email = `smoke-${Date.now()}@example.com`;
 const registered = await context.request.post(root + '/api/auth', { data: { action: 'register', name: 'Jamie Test', email, password: 'Platera-test-2048!' } });
 expect(registered.status()).toBe(200);
 const account = await (await context.request.get(root + '/api/workspace')).json();
 expect(account.business.id).toBe(initial.business.id); expect(account.user.demo).toBe(false);
 await context.request.post(root + '/api/auth', { data: { action: 'logout' } });
 const denied = await context.request.post(root + '/api/products', { data: {} }); expect(denied.status()).toBe(401);
 const invalid = await context.request.post(root + '/api/auth', { data: { action: 'login', email, password: 'wrong-password' } }); expect(invalid.status()).toBe(401);
 const login = await context.request.post(root + '/api/auth', { data: { action: 'login', email, password: 'Platera-test-2048!' } }); expect(login.status()).toBe(200);
 const business = { ...initial.business, name: 'The Test Kitchen', city: 'Toronto', province: 'Ontario', address: '100 Queen Street West' };
 const updated = await context.request.patch(root + '/api/workspace', { data: business }); expect(updated.status()).toBe(200);
 const persisted = await (await context.request.get(root + '/api/workspace')).json(); expect(persisted.business.name).toBe('The Test Kitchen');
 const created = await context.request.post(root + '/api/products', { data: { name: 'Smoked tomato soup', description: 'Roasted tomatoes and basil', price: 1250, category: 'Starters', image: '', photos: [], available: true } });
 expect(created.status()).toBe(200); const product = await created.json();
 const patched = await context.request.patch(root + '/api/products', { data: { ...product, price: 1350 } }); expect((await patched.json()).price).toBe(1350);
 const outsider = await browser.newContext(); await outsider.request.get(root + '/api/workspace');
 const isolated = await outsider.request.delete(root + '/api/products', { data: { id: product.id } }); expect(isolated.status()).toBe(404); await outsider.close();
 const upload = await context.request.post(root + '/api/assets', { multipart: { file: { name: 'test.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jXioAAAAASUVORK5CYII=', 'base64') } } });
 expect(upload.status()).toBe(200); const asset = await upload.json(); expect((await context.request.get(root + asset.url)).status()).toBe(200);
 const guest = await context.newPage(); await guest.goto(root + '/menu/' + business.id); await guest.getByRole('heading', { name: 'The Test Kitchen', exact: true }).waitFor();
 await guest.getByRole('button', { name: /Smoked tomato soup/ }).click(); await guest.locator('.viewer-canvas canvas').waitFor(); await guest.getByRole('button', { name: 'Close dialog', exact: true }).click();
 const explored = await (await context.request.get(root + '/api/workspace')).json(); expect(explored.products.find(p => p.id === product.id).views).toBe(1);
 await context.request.patch(root + '/api/workspace', { data: { ...business, published: false } }); expect((await context.request.get(root + '/api/menu/' + business.id)).status()).toBe(404);
 await context.request.patch(root + '/api/workspace', { data: { ...business, published: true } });
 expect((await context.request.delete(root + '/api/products', { data: { id: product.id } })).status()).toBe(200);
 await page.reload(); await page.getByText('Good morning, Jamie').waitFor();
 await page.getByRole('button', { name: 'My menu', exact: false }).first().click(); await page.getByPlaceholder('Find a dish…').fill('avocado'); await expect(page.locator('.product-card')).toHaveCount(1);
 await page.getByRole('button', { name: 'QR codes', exact: true }).click(); await page.locator('img.qr-image').waitFor(); expect(await page.locator('img.qr-image').getAttribute('src')).toMatch(/^data:image\/png/);
 await page.getByRole('button', { name: 'Overview', exact: true }).click(); await page.evaluate(() => document.fonts.ready); expect(await page.evaluate(() => document.fonts.check('400 12px "DM Sans"'))).toBe(true);
 await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 await page.getByRole('button', { name: 'Open navigation', exact: true }).click(); await page.getByRole('button', { name: 'My menu', exact: false }).first().click(); await expect(page.locator('.product-card')).toHaveCount(6);
 expect(errors).toEqual([]);
 console.log('PASS: registration, demo migration, login/logout, validation, CRUD, persistence, isolation, uploads, public menu, view tracking, publication, 3D, search, QR and mobile navigation.');
} finally { await browser.close(); }
