import { pgTable, text, integer, timestamp, boolean, jsonb } from 'drizzle-orm/pg-core';

export const users = pgTable('users', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), password: text('password').notNull(), demo: boolean('demo').notNull().default(false), emailVerified: boolean('email_verified').notNull().default(false) });
export const sessions = pgTable('sessions', { token: text('token').primaryKey(), userId: text('user_id').notNull().references(() => users.id), expires: timestamp('expires').notNull() });
export const verificationTokens = pgTable('verification_tokens', { token: text('token').primaryKey(), userId: text('user_id').notNull().references(() => users.id), type: text('type').notNull(), expires: timestamp('expires').notNull() });
export const businesses = pgTable('businesses', { id: text('id').primaryKey(), ownerId: text('owner_id').notNull().references(() => users.id), name: text('name').notNull(), tagline: text('tagline').notNull(), city: text('city').notNull(), province: text('province').notNull(), address: text('address').notNull(), phone: text('phone').notNull(), currency: text('currency').notNull().default('USD'), published: boolean('published').notNull().default(true), suspended: boolean('suspended').notNull().default(false), categories: jsonb('categories').$type<string[]>().notNull().default(['Starters', 'Main courses', 'Desserts', 'Drinks']) });
export const products = pgTable('products', { id: text('id').primaryKey(), businessId: text('business_id').notNull().references(() => businesses.id), name: text('name').notNull(), description: text('description').notNull(), price: integer('price').notNull(), originalPrice: integer('original_price'), category: text('category').notNull(), image: text('image').notNull(), photos: jsonb('photos').$type<string[]>().notNull().default([]), tags: jsonb('tags').$type<string[]>().notNull().default([]), model: text('model'), available: boolean('available').notNull().default(true), isDeal: boolean('is_deal').notNull().default(false), dealItems: jsonb('deal_items').$type<string[]>().notNull().default([]), views: integer('views').notNull().default(0), createdAt: timestamp('created_at').notNull().defaultNow() });
export const activities = pgTable('activities', { id: text('id').primaryKey(), businessId: text('business_id').notNull().references(() => businesses.id), text: text('text').notNull(), type: text('type').notNull(), createdAt: timestamp('created_at').notNull().defaultNow() });
export const assets = pgTable('assets', { id: text('id').primaryKey(), ownerId: text('owner_id').notNull().references(() => users.id), data: text('data').notNull(), mime: text('mime').notNull() });
