'use client';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { Camera, RotateCw, Box, Info, Loader2, X, Move, ZoomIn } from 'lucide-react';
import { Modal, money } from './ui';
import { dishTagLabel, type Product } from '@/lib/demo';
function illustrativeDish(name:string) { const group=new THREE.Group();const mat=(color:string,roughness=.7)=>new THREE.MeshStandardMaterial({color,roughness}); const add=(geometry:THREE.BufferGeometry,color:string,x:number,y:number,z:number,sx=1,sy=1,sz=1)=>{const mesh=new THREE.Mesh(geometry,mat(color));mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);return mesh;};
add(new THREE.CylinderGeometry(1.8,1.5,.14,64),'#eee9dc',0,0,0);add(new THREE.TorusGeometry(1.64,.11,12,64),'#fffaf0',0,.1,0).rotation.x=Math.PI/2;
if(name.toLowerCase().includes('burger')){add(new THREE.SphereGeometry(1.1,40,24),'#d89440',0,1,0,1,.55,1);add(new THREE.CylinderGeometry(1.05,1.05,.18,40),'#653a26',0,.57,0);add(new THREE.CylinderGeometry(1.1,1.1,.15,40),'#e7b64c',0,.72,0);add(new THREE.CylinderGeometry(1.12,1.12,.09,40),'#83a746',0,.45,0);add(new THREE.SphereGeometry(1.1,40,24),'#c48741',0,.24,0,1,.24,1);for(let i=0;i<45;i++){const a=i*2.399,r=Math.sqrt(i/45)*.95;const s=add(new THREE.SphereGeometry(.025,6,4),'#f9e5b1',Math.cos(a)*r,1+.55*Math.sqrt(1-r*r),Math.sin(a)*r,1,.4,2);s.rotation.y=a;}}
else if(name.toLowerCase().includes('cheesecake')){add(new THREE.CylinderGeometry(1.05,1.05,.15,48),'#b78a59',0,.2,0);add(new THREE.CylinderGeometry(1.05,1.05,.62,48),'#f7e2b3',0,.58,0);add(new THREE.CylinderGeometry(1.06,1.06,.09,48),'#ab3750',0,.93,0);for(let i=0;i<16;i++){const a=i*2.399,r=Math.sqrt(i/16)*.85;add(new THREE.SphereGeometry(.15,12,12),i%2?'#4b386a':'#bd3449',Math.cos(a)*r,1.08,Math.sin(a)*r);}}
else if(name.toLowerCase().includes('matcha')){add(new THREE.CylinderGeometry(.65,.48,1.8,48),'#b4c88b',0,1,0);add(new THREE.CylinderGeometry(.66,.66,.08,48),'#dce7bd',0,1.93,0);add(new THREE.CylinderGeometry(.035,.035,2.2,12),'#ece8da',.3,1.85,0).rotation.z=-.16;}
else {add(new THREE.SphereGeometry(1.44,48,32,0,Math.PI*2,Math.PI/2,Math.PI/2),'#e7dfc8',0,.56,0,1,.38,1);add(new THREE.TorusGeometry(1.44,.07,12,64),'#f7efdd',0,.55,0).rotation.x=Math.PI/2;const isPasta=name.toLowerCase().includes('pasta');for(let i=0;i<95;i++){const a=i*2.399,r=Math.sqrt(i/95)*1.22;const x=Math.cos(a)*r,z=Math.sin(a)*r,y=.47+(1-r/1.5)*.3;if(isPasta){const p=add(new THREE.TorusGeometry(.14,.045,6,12,Math.PI*1.65),'#e8c377',x,y,z);p.rotation.set(i*.8,i*.3,i);}else{const leaf=add(new THREE.SphereGeometry(.22,10,8),['#6d943e','#89ad48','#426b35','#a6b766'][i%4],x,y,z,1,.18,1.5);leaf.rotation.set(i*.3,i*.7,i*.6);}}for(let i=0;i<11;i++){const a=i*2.3,r=.4+(i%3)*.3;add(new THREE.SphereGeometry(.19,16,12),i%3===0?'#e9b55c':'#d95839',Math.cos(a)*r,.8,Math.sin(a)*r,1,.8,1);}if(name.toLowerCase().includes('burrata'))add(new THREE.SphereGeometry(.62,32,24),'#fff5d9',0,.9,0,1,.8,1);else for(let i=0;i<5;i++){const slice=add(new THREE.TorusGeometry(.42,.12,10,24,Math.PI),'#c4d77c',.35+i*.12,.88,.15,1,1,.48);slice.rotation.set(-Math.PI/2,0,.45);}}
return group;}
export default function ProductViewer({product,currency='USD',onClose}:{product:Product;currency?:string;onClose:()=>void}) { const host=useRef<HTMLDivElement>(null);const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const[cam,setCam]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[rotating,setRotating]=useState(true);const controlsRef=useRef<OrbitControls|null>(null);const groupRef=useRef<THREE.Group|null>(null);const[scale,setScale]=useState(1);
useEffect(()=>{if(!host.current)return;let disposed=false;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{setError('3D is not supported by this browser. Try a device with WebGL enabled.');setLoading(false);return;}renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;host.current.appendChild(renderer.domElement);const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,.01,100);camera.position.set(4,4.5,5);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.55,0);controls.enableDamping=true;controls.autoRotate=true;controls.autoRotateSpeed=.8;controls.minDistance=3;controls.maxDistance=12;controls.maxPolarAngle=Math.PI*.48;controlsRef.current=controls;scene.add(new THREE.HemisphereLight(0xffffff,0xb1a694,3));const light=new THREE.DirectionalLight(0xfff6e9,4);light.position.set(3,6,4);light.castShadow=true;light.shadow.mapSize.set(2048,2048);scene.add(light);const fill=new THREE.DirectionalLight(0xffffff,1.4);fill.position.set(-4,2,-2);scene.add(fill);const group=new THREE.Group();groupRef.current=group;scene.add(group);const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.ShadowMaterial({opacity:.13}));floor.rotation.x=-Math.PI/2;floor.position.y=-.1;floor.receiveShadow=true;scene.add(floor);
if(product.model){new GLTFLoader().load(product.model,gltf=>{if(disposed)return;const box=new THREE.Box3().setFromObject(gltf.scene);const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());const factor=3/Math.max(size.x,size.y,size.z);gltf.scene.position.sub(center);const normalizer=new THREE.Group();normalizer.add(gltf.scene);normalizer.scale.setScalar(factor);normalizer.position.y=size.y*factor/2;normalizer.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});group.add(normalizer);setLoading(false);},undefined,()=>{if(!disposed){setError('This model could not be loaded. Showing an illustrative preview instead.');group.add(illustrativeDish(product.name));setLoading(false);}});}else{group.add(illustrativeDish(product.name));setLoading(false);}
const resize=()=>{if(!host.current)return;const{width,height}=host.current.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(host.current);resize();renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});return()=>{disposed=true;observer.disconnect();renderer.setAnimationLoop(null);controls.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{for(const value of Object.values(m))if(value instanceof THREE.Texture)value.dispose();m.dispose();});}});renderer.dispose();renderer.domElement.remove();stream.current?.getTracks().forEach(t=>t.stop());};},[product]);
async function toggleCamera(){if(cam){stream.current?.getTracks().forEach(t=>t.stop());setCam(false);return;}try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});setCam(true);setTimeout(()=>{if(video.current){video.current.srcObject=stream.current;void video.current.play();}},50);}catch{setError('Camera access is unavailable. Please allow camera permissions or use the 3D preview.');}}
return <Modal title={product.name} subtitle="Get a taste of a new perspective." onClose={onClose} wide><div className={'viewer-stage '+(cam?'camera-active':'')}>{cam&&<video ref={video} autoPlay playsInline muted className="ar-video"/>}<div className="viewer-canvas" ref={host}/><span className="viewer-badge"><Box size={14}/>{product.model?'Interactive 3D model':'Illustrative 3D preview'}</span>{loading&&<div className="viewer-loading"><Loader2 className="spin"/> Preparing your preview…</div>}<div className="viewer-hint"><Move size={14}/>{cam?'Point at your table · drag to adjust the view':'Drag to rotate · scroll to zoom'}</div></div><div className="viewer-controls"><button className={'btn '+(cam?'primary':'')} onClick={toggleCamera}>{cam?<X size={16}/>:<Camera size={16}/>} {cam?'Close camera':'View on your table'}</button><button className="btn" onClick={()=>{setRotating(!rotating);if(controlsRef.current)controlsRef.current.autoRotate=!rotating;}}><RotateCw size={16}/>{rotating?'Pause rotation':'Auto rotate'}</button><label className="scale-control"><ZoomIn size={17}/><input aria-label="Model size" type="range" min=".4" max="1.7" step=".05" value={scale} onChange={e=>{const n=Number(e.target.value);setScale(n);groupRef.current?.scale.setScalar(n);}}/></label></div>{error&&<div className="error-message">{error}</div>}<div className="viewer-details"><div><span className="eyebrow">{product.category}</span><p>{product.description}</p>{product.tags.length>0&&<div style={{display:'flex',flexWrap:'wrap',gap:5,marginTop:10}}>{product.tags.map(t=><span key={t} className="status-pill">{dishTagLabel(t)}</span>)}</div>}</div><div className="price-row">{product.originalPrice?<span className="was">{money(product.originalPrice,currency)}</span>:null}<strong>{money(product.price,currency)}</strong></div></div><div className="viewer-disclaimer"><Info size={15}/>{cam?'Live camera overlay with manual positioning; automatic surface detection is not enabled.':product.model?'Explore the restaurant’s uploaded 3D model. Appearance and portions may vary.':'This is a stylized sample, not a scan of this dish. Owners can upload a photorealistic GLB model.'}</div></Modal>;}
