'use client';
import { useEffect, useState, type ReactNode } from 'react';
import { X, Download, Copy, Check, ExternalLink, Sprout } from 'lucide-react';
import QRCode from 'qrcode';
export function Brand({small=false}:{small?:boolean}) { return <div className={'brand '+(small?'small':'')}><span className="brand-symbol"><Sprout size={25} strokeWidth={1.7}/></span><span>platera<span className="brand-dot">.</span></span></div>; }
export function Modal({title,subtitle,children,onClose,wide=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;wide?:boolean}) { useEffect(()=>{ const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();}; document.addEventListener('keydown',key); const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=previous;}; },[onClose]);return <div className="modal-overlay" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><section role="dialog" aria-modal="true" aria-label={title} className={'modal '+(wide?'modal-wide':'')}><header className="modal-header"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-btn" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></header>{children}</section></div>; }
export function QRPanel({id,name,compact=false}:{id:string;name:string;compact?:boolean}) { const [image,setImage]=useState('');const[copied,setCopied]=useState(false);const[url,setUrl]=useState('');useEffect(()=>{const value=window.location.origin+'/menu/'+id;setUrl(value);QRCode.toDataURL(value,{width:800,margin:2,color:{dark:'#294c3b',light:'#ffffff'},errorCorrectionLevel:'M'}).then(setImage);},[id]);return <div className={'qr-panel '+(compact?'compact':'')}><div className="qr-paper">{!compact&&<><Brand small/><h3>{name}</h3><p>A little scan. A delicious discovery.</p></>}{image?<img src={image} alt={'QR code for '+name} className="qr-image"/>:<div className="skeleton qr-image"/>}{!compact&&<><strong>Scan. Explore. Enjoy.</strong><p>Experience our menu in a new dimension.</p></>}</div><div className="qr-actions"><a className="btn primary" href={image||undefined} download={name.toLowerCase().replaceAll(' ','-')+'-menu-qr.png'}><Download size={16}/>{compact?'Download QR':'Download QR code'}</a><button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{window.prompt('Copy your menu link',url);}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied!':'Copy link'}</button></div>{!compact&&<a className="text-link" href={url} target="_blank" rel="noreferrer">Open guest menu <ExternalLink size={14}/></a>}</div>; }
export function Empty({title,text,children}:{title:string;text:string;children?:ReactNode}) {return <div className="empty-state"><Sprout size={34}/><h3>{title}</h3><p>{text}</p>{children}</div>;}
export async function request<T>(url:string,method='GET',body?:unknown):Promise<T> { const res=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined}); const data=await res.json();if(!res.ok)throw new Error(data.error||'Something went wrong. Please try again.');return data; }
const CURRENCY_LOCALES:Record<string,string>={USD:'en-US',PKR:'ur-PK',INR:'en-IN',AUD:'en-AU',EUR:'en-IE',GBP:'en-GB',SAR:'en-SA',AED:'en-AE',QAR:'en-QA',KWD:'en-KW',BHD:'en-BH',OMR:'en-OM'};
export const money=(cents:number,currency:string='USD')=>{try{return new Intl.NumberFormat(CURRENCY_LOCALES[currency]||'en-US',{style:'currency',currency}).format(cents/100);}catch{return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100)+' '+currency;}};
